#!/usr/bin/env python3
# Cannon Fodder In-Game Level Editor V1.1
# Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
# Licensed under the MIT License. See the LICENSE file for details.
"""Assemble the editor and the WHDLoad slave and embed them in patch.py.

Usage: python3 build.py [--vasm PATH] [--vlink PATH]

Requires the vasm 68000 assembler with Motorola syntax (vasmm68k_mot) and the
vlink linker. No game file is read: the patch table records only where the
editor changes the game's main program, the SHA-256 of the bytes it expects
there and the bytes it writes. Only the section of patch.py between the
"GENERATED BY build.py" markers is written again, so users of patch.py need
only Python 3.

The editor has three parts:
- the resident (src/editor/resident/bootstrap.s), which patch.py appends to
  the game's main program, with four small bodies that replace game code in
  place (hill_body, campaign_body, base_attributes, resource_loaders);
- seventeen overlay modules (src/editor/modules), which the slave loads from
  the install's Custom directory into one shared bank when they are needed;
- the hooks (src/hooks.json), the jumps from the game's code into the editor
  and the slave's host patches.
The slave (src/whdload/slave.s) is assembled with the size of the patched
main program.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
import re
import struct
import subprocess
import tempfile
import textwrap
import zlib

ROOT = Path(__file__).resolve().parent
EDITOR = ROOT / 'src/editor'
WHDLOAD = ROOT / 'src/whdload'
INCLUDE = EDITOR / 'include'
HOOKS = ROOT / 'src/hooks.json'
PATCH = ROOT / 'patch.py'
VERSION = '1.1'
HEADER = f'Cannon Fodder In-Game Level Editor V{VERSION}'
BEGIN = '# BEGIN GENERATED BY build.py - do not edit by hand\n'
END = '# END GENERATED BY build.py\n'

# The overlay modules in the order of the editor's catalog: the file in
# Custom, the identity in its header, the source, the bytes kept free at the
# end of the module bank and extra include directories.
TRANSACTIONS = 'modules/object_transactions'
MODULES = [
    ('cf_storage.mod', b'STG1', 'modules/storage/storage.s', 0, ()),
    ('cf_browser.mod', b'BROW', 'modules/browser/browser.s', 0, ()),
    ('controller.mod', b'CTRL', 'modules/controller/controller.s', 0, ()),
    ('cf_save.mod', b'SVR1', 'modules/storage/save.s', 0, ()),
    ('cf_editor.mod', b'EDTR', 'modules/editor/editor.s', 0, (TRANSACTIONS,)),
    ('cf_tiles.mod', b'TILE', 'modules/tiles/tiles.s', 0, ()),
    ('cf_fill.mod', b'FILL', 'modules/fill/fill.s', 0, (TRANSACTIONS,)),
    ('cf_resize.mod', b'RSZE', 'modules/resize/resize.s', 0, ()),
    ('cf_menu.mod', b'MENU', 'modules/menu/menu.s', 0, ()),
    ('cf_tmpl.mod', b'TMPL', 'modules/template/template.s', 4992, ()),
    ('cf_open.mod', b'OPEN', 'modules/open/open.s', 4928, ()),
    ('cf_files.mod', b'FOPS', 'modules/live_files/files.s', 2304, ()),
    ('cf_object.mod', b'OBJV', 'modules/editor/object_view.s', 0, (TRANSACTIONS,)),
    ('cf_opal.mod', b'OPAL', 'modules/object_palette/palette.s', 0, ()),
    ('cf_phase.mod', b'PHAS', 'modules/phase_list/phase.s', 1344, ()),
    ('cf_valid.mod', b'VALD', 'modules/validation/validation.s', 2048, ()),
    ('cf_test.mod', b'TST1', 'modules/test/test.s', 4928, ()),
]


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def constants() -> dict[str, int]:
    """The addresses and sizes shared with the assembly sources."""
    result = {}
    for name in ('fodders.i', 'layout.i', 'module.i'):
        for line in (INCLUDE / name).read_text().splitlines():
            declaration = line.split(';', 1)[0].strip()
            if not declaration:
                continue
            match = re.fullmatch(r'([A-Za-z][A-Za-z0-9_]*)\s+equ\s+\$([0-9a-fA-F]+)', declaration)
            if match is None or match[1] in result:
                raise SystemExit(f'invalid or duplicate constant in {name}: {line}')
            result[match[1]] = int(match[2], 16)
    return result


def check_layout(values: dict[str, int]) -> None:
    """The memory partitions must tile their banks without gaps or overlaps."""
    layouts = {
        'RESIDENT': [('RESIDENT', 'GATE'), ('SNAPSHOT', 'SNAPSHOT'), ('SESSION', 'SESSION'),
                     ('METADATA', 'METADATA'), ('IO', 'IO'), ('UI', 'UI'), ('SPT', 'SPT'),
                     ('SPARE', 'SPARE'), ('GUARD', 'GUARD')],
        'MODULE': [('MODULE', 'MODULE'), ('UNDO', 'UNDO'), ('WORK', 'WORK'),
                   ('MODULE_GUARD', 'MODULE_GUARD')],
        'SERIALIZER': [('SERIALIZER', 'SERIALIZER'), ('READBACK', 'READBACK'),
                       ('SERIAL_WORK', 'SERIAL_WORK'), ('UNDO', 'UNDO'), ('MANIFEST', 'MANIFEST'),
                       ('MODULE_GUARD', 'MODULE_GUARD')],
    }
    for mode, rows in layouts.items():
        resident = mode == 'RESIDENT'
        cursor = first = values['EDITOR_RESIDENT_BASE' if resident else 'EDITOR_MODULE_BASE']
        for base, capacity in rows:
            address, size = values[f'EDITOR_{base}_BASE'], values[f'EDITOR_{capacity}_BYTES']
            if address != cursor or address & 1 or size <= 0 or size & 1:
                raise SystemExit(f'invalid {mode.lower()} partition at {base}')
            cursor += size
        end = values['EDITOR_RESIDENT_END' if resident else 'EDITOR_MODULE_END']
        total = values['EDITOR_RESIDENT_BYTES' if resident else 'EDITOR_BANK_BYTES']
        if cursor != end or cursor - first != total:
            raise SystemExit(f'invalid {mode.lower()} bank boundary')
    if (values['EDITOR_RESIDENT_END'] != values['EDITOR_DIRECTORY_BASE']
            or values['EDITOR_DIRECTORY_BASE'] + values['EDITOR_DIRECTORY_BYTES'] != values['EDITOR_MODULE_BASE']
            or values['EDITOR_DIRECTORY_RECORDS'] * 32 != values['EDITOR_DIRECTORY_BYTES']):
        raise SystemExit('the directory cache boundaries disagree')


def parse_map(text: str) -> tuple[list[tuple[int, int]], dict[str, int]]:
    """The sections (base, size) and symbols of a vlink map."""
    sections, symbols = [], {}
    for line in text.splitlines():
        section = re.fullmatch(r'  ([0-9a-fA-F]+) (\S+)\s+\(size ([0-9a-fA-F]+)\)', line)
        symbol = re.fullmatch(r'  0x([0-9a-fA-F]+) ([A-Za-z_][A-Za-z0-9_]*): .*', line)
        if section:
            sections.append((int(section[1], 16), int(section[3], 16)))
        if symbol:
            if symbol[2] in symbols:
                raise SystemExit(f'duplicate linker symbol: {symbol[2]}')
            symbols[symbol[2]] = int(symbol[1], 16)
    if not sections or not symbols:
        raise SystemExit('the linker map has no sections or symbols')
    return sections, symbols


class Assembler:
    def __init__(self, vasm: str, vlink: str, work: Path):
        self.vasm, self.vlink, self.work = vasm, vlink, work

    def link(self, name: str, source: Path, base: int, capacity: int,
             includes: tuple[Path, ...] = ()) -> tuple[bytes, dict[str, int]]:
        """Assemble and link one part as raw code at its fixed address."""
        obj, binary = self.work / f'{name}.o', self.work / f'{name}.bin'
        paths = (INCLUDE, source.parent, *includes)
        subprocess.run([self.vasm, '-quiet', '-Fvobj', '-m68000', '-no-opt',
                        *(arg for path in paths for arg in ('-I', str(path))),
                        '-o', str(obj), str(source)], check=True)
        link = subprocess.run([self.vlink, '-b', 'rawbin1', '-Ttext', hex(base), '-M', '-Z',
                               '-o', str(binary), str(obj)],
                              check=True, capture_output=True, text=True)
        payload = binary.read_bytes()
        sections, symbols = parse_map(link.stdout)
        cursor = base
        for start, size in sorted(sections):
            if start < cursor or start & 1 or (cursor == base and start != base):
                raise SystemExit(f'{name}: misplaced or overlapping sections')
            cursor = start + size
        if not 0 < cursor - base <= capacity or len(payload) != cursor - base:
            raise SystemExit(f'{name}: needs {cursor - base} bytes, has room for {capacity}')
        return payload, symbols

    def slave(self, main_size: int) -> bytes:
        output = self.work / 'CannonFodder.slave'
        subprocess.run([self.vasm, '-quiet', '-m68000', '-no-opt', '-Fhunkexe', '-nosym',
                        '-I', str(WHDLOAD), '-I', str(INCLUDE), f'-DMAIN_SIZE={main_size}',
                        '-o', str(output), str(WHDLOAD / 'slave.s')], check=True)
        blob = output.read_bytes()
        code = struct.unpack_from('>I', blob, 28)[0] * 4
        if blob[:20] != struct.pack('>5I', 0x3F3, 0, 1, 0, 0) or blob[32 + code:] != struct.pack('>I', 0x3F2):
            raise SystemExit('the slave must be one code hunk without relocations')
        return blob


def package_module(payload: bytes, identity: bytes, values: dict[str, int]) -> bytes:
    """Check a linked module's header and fill in its body CRC-32."""
    size = values['MODULE_HEADER_BYTES']
    magic, abi, header, ident, base, length, entry, crc, flags = struct.unpack_from('>IHH6I', payload)
    if (magic != values['MODULE_MAGIC'] or abi != values['MODULE_ABI'] or header != size
            or ident != int.from_bytes(identity, 'big') or base != values['EDITOR_MODULE_BASE']
            or length != len(payload) or length & 1 or length > values['EDITOR_SERIALIZER_BYTES']
            or flags or not size <= entry < length or entry & 1 or crc):
        raise SystemExit(f'invalid module header: {identity.decode()}')
    result = bytearray(payload)
    struct.pack_into('>I', result, values['MODULE_CRC_OFFSET'], zlib.crc32(payload[size:]))
    return bytes(result)


def runtime_extension(resident: bytes, values: dict[str, int]) -> tuple[int, int]:
    """The resident's offset in the bytes appended to the main program, and
    the length of that extension: zeros from the end of the program to the
    end of the resident bank, with the resident's code in place."""
    start = values['FODDERS_BASE'] + values['FODDERS_IMAGE_BYTES']
    base, end = values['EDITOR_RESIDENT_BASE'], values['EDITOR_RESIDENT_END']
    if (start & 1 or not start <= base < end or not resident or len(resident) & 1
            or len(resident) > values['EDITOR_GATE_BYTES']):
        raise SystemExit('invalid resident extent')
    return base - start, end - start


def patch_rows(table: dict, values: dict[str, int], symbols: dict[str, int],
               components: dict[str, tuple[int, bytes]]) -> list[tuple]:
    """The patches to the main program: (name, offset, length, SHA-256 of
    the original bytes, replacement bytes in hex). Protected ranges keep
    their bytes."""
    rows, taken = [], []

    def claim(name: str, offset: int, length: int) -> None:
        if offset < 0 or offset & 1 or length <= 0 or length & 1 \
                or offset + length > values['FODDERS_IMAGE_BYTES']:
            raise SystemExit(f'invalid patch range: {name}')
        if any(offset < end and start < offset + length for start, end in taken):
            raise SystemExit(f'overlapping patch ranges: {name}')
        taken.append((offset, offset + length))

    for item in table['protected']:
        offset = values[item['address']] - values['FODDERS_BASE']
        claim(item['name'], offset, item['bytes'])
        rows.append((item['name'], offset, item['bytes'], item['expected_sha256'], None))
    for item in table['hooks']:
        address = values[item['address']]
        offset, length = address - values['FODDERS_BASE'], item['bytes']
        claim(item['name'], offset, length)
        # A replaced span must end where the game continues after it.
        resume = values[item['resume']]
        if item['opcode'] in ('raw', 'component') and resume != address + length:
            raise SystemExit(f'invalid resume address: {item["name"]}')
        if item['opcode'] == 'raw':
            replacement = bytes.fromhex(item['replacement'])
        elif item['opcode'] in ('jmp', 'jsr'):
            padding = length - 6
            if padding < 0 or (padding and item.get('padding') != 'nop') \
                    or item.get('padding') not in (None, 'nop'):
                raise SystemExit(f'invalid hook padding: {item["name"]}')
            target = symbols[item['target']]
            if target & 1 or not 0 <= target <= 0xFFFFFF:
                raise SystemExit(f'invalid hook target: {item["name"]}')
            replacement = struct.pack('>HI', 0x4EF9 if item['opcode'] == 'jmp' else 0x4EB9, target)
            replacement += bytes.fromhex('4e71') * (padding // 2)
        elif item['opcode'] == 'component':
            base, replacement = components[item['component']]
            if base != address:
                raise SystemExit(f'misplaced hook component: {item["name"]}')
        else:
            raise SystemExit(f'unsupported hook: {item["name"]}')
        if len(replacement) != length:
            raise SystemExit(f'hook replacement length differs: {item["name"]}')
        rows.append((item['name'], offset, length, item['expected_sha256'], replacement.hex()))
    # A host patch may coincide with an editor hook only if both write the
    # same bytes.
    editor = [row for row in rows if row[4] is not None]
    hosts = []
    for item in table['host']:
        offset, length = item['offset'], item['bytes']
        replacement = bytes.fromhex(item['replacement'])
        if len(replacement) != length:
            raise SystemExit(f'host patch length differs: {item["purpose"]}')
        same = [row for row in editor if row[1] <= offset and offset + length <= row[1] + row[2]]
        if same:
            row = same[0]
            if bytes.fromhex(row[4])[offset - row[1]:offset - row[1] + length] != replacement:
                raise SystemExit(f'host patch conflicts with a hook: {item["purpose"]}')
            continue
        if any(offset < end and start < offset + length for start, end in taken):
            raise SystemExit(f'host patch overlaps a hook: {item["purpose"]}')
        taken.append((offset, offset + length))
        hosts.append((item['purpose'], offset, length, item['expected_sha256'], item['replacement']))
    return sorted(rows + hosts, key=lambda row: row[1])


def build(vasm: str, vlink: str) -> tuple[dict, dict[str, bytes]]:
    values = constants()
    check_layout(values)
    table = json.loads(HOOKS.read_text())
    if table.get('schema') != 1 or table.get('image') != 'FODDERC' \
            or table.get('input_bytes') != values['FODDERS_IMAGE_BYTES']:
        raise SystemExit('unsupported hook table')
    with tempfile.TemporaryDirectory() as temp:
        work = Path(temp)
        tools = Assembler(vasm, vlink, work)
        resident, linked = tools.link('resident', EDITOR / 'resident/bootstrap.s',
                                      values['EDITOR_RESIDENT_BASE'], values['EDITOR_GATE_BYTES'])
        if any(linked.get(name) != value for name, value in values.items()):
            raise SystemExit('the assembler constants disagree with the build constants')
        if (linked['editor_resident_start'] != values['EDITOR_RESIDENT_BASE']
                or linked['editor_resident_end'] != values['EDITOR_RESIDENT_BASE'] + len(resident)):
            raise SystemExit('the resident boundary symbols disagree with its sections')
        resident_offset, extension_bytes = runtime_extension(resident, values)
        # The in-place bodies call into the resident by its linked addresses.
        (work / 'resident_symbols.i').write_text(
            '; Generated from the resident linker map. Do not edit.\n' + ''.join(
                f'RESIDENT_{name} equ ${address:08X}\n' for name, address in sorted(linked.items())
                if name.startswith(('editor_', 'policy_', 'session_'))))
        hill, _ = tools.link('hill_body', EDITOR / 'resident/hill_body.s',
                             values['native_hill_body'], 192)
        campaign, _ = tools.link('campaign_body', EDITOR / 'resident/campaign_body.s',
                                 values['native_controller_body'], 96, (work,))
        if values['native_controller_body'] != values['campaign_list_hook'] + 6:
            raise SystemExit('the campaign body does not follow its entry jump')
        attributes, _ = tools.link(
            'base_attributes', EDITOR / 'resident/base_attributes.s', values['native_base_attributes'],
            values['native_base_attributes_end'] - values['native_base_attributes'])
        loaders, loader_symbols = tools.link(
            'resource_loaders', EDITOR / 'resident/resource_loaders.s', values['native_resource_raw'],
            values['native_resource_loaders_end'] - values['native_resource_raw'], (work,))
        if (loader_symbols['editor_resource_ilbm'] != values['native_resource_ilbm']
                or loader_symbols['editor_resource_retry_native'] != values['native_resource_retry_body']
                or loader_symbols['editor_resource_loaders_end'] != values['native_resource_loaders_end']):
            raise SystemExit('the resource loader entry points moved')
        components = {
            'resource_loaders': (values['native_resource_raw'], loaders),
            'base_attributes': (values['native_base_attributes'], attributes),
            'hill_body': (values['native_hill_body'], hill),
            'campaign_listing': (values['campaign_list_hook'],
                                 struct.pack('>HI', 0x4EF9, linked['editor_campaign_list']) + campaign),
        }
        blobs = {'resident': resident}
        catalog = []
        for filename, identity, source, reserved, includes in MODULES:
            payload, _ = tools.link(filename[:-4], EDITOR / source,
                                    values['EDITOR_MODULE_BASE'],
                                    values['EDITOR_SERIALIZER_BYTES'] - reserved,
                                    tuple(EDITOR / path for path in includes))
            blobs[filename] = package_module(payload, identity, values)
            catalog.append((filename, int.from_bytes(identity, 'big'), values['EDITOR_MODULE_BASE'],
                            values['EDITOR_SERIALIZER_BYTES']))
        rows = patch_rows(table, values, linked, components)
        main_size = values['FODDERS_IMAGE_BYTES'] + extension_bytes
        blobs['CannonFodder.slave'] = tools.slave(main_size)
    generated = {
        'MAIN': {'name': table['image'], 'bytes': table['input_bytes'],
                 'sha256': table['input_sha256'], 'extension_bytes': extension_bytes,
                 'resident_offset': resident_offset, 'output_bytes': main_size},
        'PATCHES': rows, 'MODULES': catalog,
    }
    return generated, blobs


def check_version() -> None:
    for path in sorted(ROOT.glob('src/**/*.[si]')) + [PATCH, Path(__file__).resolve()]:
        lines = path.read_text().splitlines()
        first = lines[1 if path.suffix == '.py' else 0]
        if HEADER not in first:
            raise SystemExit(f'{path.relative_to(ROOT)}: its header does not name V{VERSION}')


def embed(generated: dict, blobs: dict[str, bytes]) -> None:
    lines = [BEGIN]
    for name, value in generated.items():
        if isinstance(value, dict):
            lines.append(f'{name} = {{\n')
            lines += [f'    {key!r}: {item!r},\n' for key, item in value.items()]
            lines.append('}\n')
        else:
            lines.append(f'{name} = [\n')
            lines += [f'    {row!r},\n' for row in value]
            lines.append(']\n')
    lines.append('BLOB_SHA256 = {\n')
    lines += [f'    {name!r}: {sha256(data)!r},\n' for name, data in blobs.items()]
    lines.append('}\n# Each blob is zlib-compressed, then base64-encoded.\nBLOBS = {\n')
    for name, data in blobs.items():
        text = base64.b64encode(zlib.compress(data, 9)).decode('ascii')
        lines.append(f'    {name!r}: (\n')
        lines += [f"        '{part}'\n" for part in textwrap.wrap(text, 72)]
        lines.append('    ),\n')
    lines += ['}\n', END]
    source = PATCH.read_text()
    start, end = source.index(BEGIN), source.index(END) + len(END)
    PATCH.write_text(source[:start] + ''.join(lines) + source[end:])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--vasm', default='vasmm68k_mot', help='the vasm executable')
    parser.add_argument('--vlink', default='vlink', help='the vlink executable')
    args = parser.parse_args()
    check_version()
    generated, blobs = build(args.vasm, args.vlink)
    embed(generated, blobs)
    for name, data in blobs.items():
        print(f'{name}: {len(data)} bytes, SHA-256 {sha256(data)}')
    print(f'{len(generated["PATCHES"])} patches; Main.bin {generated["MAIN"]["output_bytes"]} bytes')


if __name__ == '__main__':
    main()
