; Cannon Fodder In-Game Level Editor V1.1
; Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
; Licensed under the MIT License. See the LICENSE file for details.

CONTROLLER_MODULE_ID        equ $4354524C
CONTROLLER_TRANSACTION_TAG  equ $43545831
CONTROLLER_TRANSACTION      equ EDITOR_SESSION_BASE+72
CONTROLLER_STAGE            equ EDITOR_SESSION_BASE+76
CONTROLLER_OPERATION        equ EDITOR_SESSION_BASE+78
CONTROLLER_SOURCE_PHASE     equ EDITOR_SESSION_BASE+80
CONTROLLER_TARGET_PHASE     equ EDITOR_SESSION_BASE+82
CONTROLLER_ACCOUNTED        equ EDITOR_SESSION_BASE+84
CONTROLLER_RESERVED         equ EDITOR_SESSION_BASE+86
CONTROLLER_MANIFEST_CRC      equ EDITOR_SESSION_BASE+88
CONTROLLER_GENERATION        equ EDITOR_SESSION_BASE+92
CONTROLLER_STAGE_ARMED       equ 0
CONTROLLER_STAGE_RESULT      equ 1
CONTROLLER_STAGE_STORAGE     equ 2
CONTROLLER_OP_RETRY          equ 1
CONTROLLER_OP_NEXT           equ 2
CONTROLLER_SAVED_POLICY      equ EDITOR_SESSION_BASE+224
        ifne CONTROLLER_GENERATION+4-SESSION_CHECKPOINT_BASE
        fail "Controller transaction must end at checkpoint base"
        endif
