; Cannon Fodder In-Game Level Editor V1.0
; Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
; Licensed under the MIT License. See the LICENSE file for details.

STORAGE_MODULE_ID         equ $53544731
STORAGE_CONTEXT          equ EDITOR_IO_BASE+64
STORAGE_COMMAND          equ EDITOR_IO_BASE+144
STORAGE_SELECTED         equ EDITOR_IO_BASE+146
STORAGE_READY            equ EDITOR_IO_BASE+148
STORAGE_STATUS           equ EDITOR_IO_BASE+152
STORAGE_STAGE            equ EDITOR_IO_BASE+154
STORAGE_PHASE_COUNT      equ EDITOR_IO_BASE+156
STORAGE_RESERVED         equ EDITOR_IO_BASE+158
STORAGE_ERRORS           equ EDITOR_IO_BASE+160
STORAGE_REVIEWS          equ EDITOR_IO_BASE+164
STORAGE_RESULT           equ EDITOR_IO_BASE+168
STORAGE_MANIFEST_NAME    equ EDITOR_IO_BASE+200
STORAGE_MANIFEST_LENGTH  equ EDITOR_IO_BASE+216
STORAGE_PRIVATE_RESERVED equ EDITOR_IO_BASE+220
STORAGE_PHASE            equ EDITOR_IO_BASE+222
STORAGE_IO_END           equ EDITOR_IO_BASE+224
STORAGE_CANDIDATE        equ EDITOR_SERIAL_WORK_BASE+1032
STORAGE_PARSER_WORK      equ EDITOR_READBACK_BASE+1024
STORAGE_PAYLOAD_WORK     equ EDITOR_SERIAL_WORK_BASE
STORAGE_OLD_METADATA     equ EDITOR_READBACK_BASE+512
STORAGE_OLD_SPT          equ EDITOR_READBACK_BASE+1024

STORAGE_CMD_READ         equ 1
STORAGE_CMD_INSPECT      equ 2
STORAGE_CMD_VALIDATE     equ 3
STORAGE_STAGE_MANIFEST   equ 1
STORAGE_STAGE_PARSE      equ 2
STORAGE_STAGE_MAP        equ 3
STORAGE_STAGE_SPT        equ 4
STORAGE_STAGE_PAYLOAD    equ 5
STORAGE_STAGE_PUBLISH    equ 6
