; Cannon Fodder In-Game Level Editor V1.0
; Copyright (c) 2026 Timo Heimonen <timo.heimonen@proton.me>
; Licensed under the MIT License. See the LICENSE file for details.

; Local immutable snapshots and disposable stage share the existing16KiB slot.
PHL_RESERVED equ 1344
PHL_ORIGINAL equ EDITOR_MODULE_BASE+EDITOR_SERIALIZER_BYTES-PHL_RESERVED
PHL_OWNER equ PHL_ORIGINAL+384
PHL_STAGE_SPT equ PHL_OWNER+128
PHL_STAGE_METADATA equ PHL_STAGE_SPT+432
PHL_CACHE equ PHL_STAGE_SPT
PHL_ROW_BYTES equ 92
PHL_ROW_TITLE equ 0
PHL_ROW_NAME equ 64
PHL_ROW_BYTES_MAP equ 80
PHL_ROW_STATUS equ 82
PHL_ROW_CRC equ 84
PHL_ROW_SIZE equ 88

PHL_MAGIC equ EDITOR_UI_BASE
PHL_MAP equ EDITOR_UI_BASE+4
PHL_FOCUS equ EDITOR_UI_BASE+12
PHL_SOURCE_COUNT equ EDITOR_UI_BASE+16
PHL_CURRENT_SIZE equ EDITOR_UI_BASE+18
PHL_DIRECTORY_CRC equ EDITOR_UI_BASE+22
PHL_READY equ EDITOR_UI_BASE+26
PHL_STATUS equ EDITOR_UI_BASE+28
PHL_INTENT equ EDITOR_UI_BASE+30
PHL_BLANK_FAMILY equ EDITOR_UI_BASE+96
PHL_BLANK_WIDTH equ EDITOR_UI_BASE+98
PHL_BLANK_HEIGHT equ EDITOR_UI_BASE+100
PHL_TEST_TAG equ PHL_STAGE_METADATA+384
PHL_TEST_ORIGINAL equ PHL_TEST_TAG+4
PHL_TESTED equ PHL_TEST_TAG+5
PHL_TEST_INITIAL equ PHL_TEST_TAG+6
        ifgt PHL_TEST_INITIAL+1-EDITOR_MODULE_BASE-EDITOR_SERIALIZER_BYTES
        fail "Phase tested state exceeds reserved tail"
        endif
PHL_TAG equ $50484C31
PHL_ERROR_STATE equ -124
PHL_ERROR_STALE equ -125
PHL_ERROR_SOURCE equ -126
PHL_ERROR_PRIVATE equ -127

        ifgt PHL_STAGE_METADATA+384-EDITOR_MODULE_BASE-EDITOR_SERIALIZER_BYTES
        fail "Phase stage exceeds module allocation"
        endif
        ifgt PHL_CACHE+PHL_ROW_BYTES*6-PHL_STAGE_METADATA-384
        fail "Phase preview cache exceeds disposable stage"
        endif
